name: vinegar
tolerance: 5.0
container: liquid
pouring_position: corner
controller:
  type: pd
  morphology: 
  p_gain: 0.002
  d_gain: 0.015
  max_acc_scaling: 2
  max_vel_scaling: 4
  rot_axis: [0.7071, 0, -0.7071]
  shaking: False
